export default {
  data: [
    {
      id: 1001,
      parentId: -1,
      cqlFilter: null,
      cnName: '公益林',
      type: 1,
      enable: 0,
      icon: null,
      enName: 'forestry_public_welfare_style',
      sorting: 1001,
      remark: null,
      media: null,
      fillColor: '#FFFFFF',
      fillOpacity: '0',
      strokeColor: '#000000',
      strokeWidth: '0',
      geoId: 200078,
      geoBsm: 'forestry_public_welfare_2022_1726526712127262721',
      workArea: 'lincao_resources_area',
      dataPool: 'lincao_resources_db',
      mapUrl: 'http://192.168.3.11:8001/geoserver/',
      forestCode: 'forestry_public_welfare',
      columnName: 'tbbh',
      filterCondition: null,
      inOrEquals: 25,
      childList: [
        {
          id: 1002,
          parentId: 1001,
          cqlFilter: null,
          cnName: '森林类别',
          type: 1,
          enable: 0,
          icon: null,
          enName: 'gyl_dl',
          sorting: 1002,
          remark: null,
          media: null,
          fillColor: null,
          fillOpacity: null,
          strokeColor: null,
          strokeWidth: null,
          geoId: 200078,
          geoBsm: '',
          workArea: '',
          dataPool: 'lincao_resources_db',
          mapUrl: 'http://192.168.3.10:8001/geoserver/',
          forestCode: 'forestry_public_welfare',
          columnName: null,
          filterCondition: '',
          inOrEquals: 0,

          childList: [
            {
              id: 1003,
              parentId: 1002,
              cqlFilter: null,
              cnName: '乔木林地',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'gyl_qmld',
              sorting: 1003,
              remark: null,
              media: null,
              fillColor: '#81C35D',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: '0',
              geoId: 200078,
              geoBsm: 'fireprot_impt_point_gisview666',
              workArea: 'senlinfanghuo',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_public_welfare',
              columnName: 'di_lei',
              filterCondition: '030100',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 1004,
              parentId: 1002,
              cqlFilter: "di_lei  = '030200' ",
              cnName: '竹林地',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'gyl_zld',
              sorting: 1004,
              remark: null,
              media: null,
              fillColor: '#97CFB2',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200078,
              geoBsm: 'forestry_public_welfare_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_public_welfare',
              columnName: 'di_lei',
              filterCondition: '030200',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 1005,
              parentId: 1002,
              cqlFilter: "\r\ndi_lei  IN ( '0303','030301','030302') ",
              cnName: '灌木林地',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'gyl_gmld',
              sorting: 1005,
              remark: null,
              media: null,
              fillColor: '#83C666',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200078,
              geoBsm: 'forestry_public_welfare_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_public_welfare',
              columnName: 'di_lei',
              filterCondition: '0303',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 1006,
              parentId: 1002,
              cqlFilter: "di_lei  = '0304'",
              cnName: '红树林地',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'gyl_hsld',
              sorting: 1006,
              remark: null,
              media: null,
              fillColor: '#64B968',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200078,
              geoBsm: 'forestry_public_welfare_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_public_welfare',
              columnName: 'di_lei',
              filterCondition: '0304',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 1010,
              parentId: 1002,
              cqlFilter:
                "di_lei IN ('030401','030402','030403','030301','030302')",
              cnName: '其他林地',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'gyl_qtld',
              sorting: 1010,
              remark: null,
              media: null,
              fillColor: '\t#008080',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: '0',
              geoId: 200078,
              geoBsm: 'forestry_public_welfare_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_public_welfare',
              columnName: 'di_lei',
              filterCondition: '030401,030402,030403',
              inOrEquals: 1,
              childList: []
            }
          ]
        },
        {
          id: 1037,
          parentId: 1001,
          cqlFilter: null,
          cnName: '公益林事权等级',
          type: 1,
          enable: 0,
          icon: null,
          enName: 'gyl_sq',
          sorting: 1037,
          remark: null,
          media: null,
          fillColor: null,
          fillOpacity: null,
          strokeColor: null,
          strokeWidth: null,
          geoId: 200078,
          geoBsm: 'forestry_public_welfare_2022_1726526712127262721',
          workArea: 'lincao_resources_area',
          dataPool: 'lincao_resources_db',
          mapUrl: 'http://192.168.3.11:8001/geoserver/',
          forestCode: 'forestry_public_welfare',
          columnName: null,
          filterCondition: '',
          inOrEquals: 0,
          childList: [
            {
              id: 1038,
              parentId: 1037,
              cqlFilter: '',
              cnName: '国家公益林',
              type: 1,
              enable: 0,
              icon: null,
              enName: 'gyl_gjgyl',
              sorting: 1038,
              remark: null,
              media: null,
              fillColor: null,
              fillOpacity: null,
              strokeColor: null,
              strokeWidth: null,
              geoId: 200078,
              geoBsm: 'forestry_public_welfare_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_public_welfare',
              columnName: null,
              filterCondition: null,
              inOrEquals: 0,
              childList: [
                {
                  id: 1039,
                  parentId: 1038,
                  cqlFilter: "gjgyl_bhdj = '1'",
                  cnName: 'I级',
                  type: 0,
                  enable: 0,
                  icon: null,
                  enName: 'gyl_yj',
                  sorting: 1039,
                  remark: null,
                  media: null,
                  fillColor: '#0083FF',
                  fillOpacity: '0.8',
                  strokeColor: null,
                  strokeWidth: null,
                  geoId: 200078,
                  geoBsm: 'forestry_public_welfare_2022_1726526712127262721',
                  workArea: 'lincao_resources_area',
                  dataPool: 'lincao_resources_db',
                  mapUrl: 'http://192.168.3.11:8001/geoserver/',
                  forestCode: 'forestry_public_welfare',
                  columnName: 'gjgyl_bhdj',
                  filterCondition: '1',
                  inOrEquals: 0,
                  childList: []
                },
                {
                  id: 1040,
                  parentId: 1038,
                  cqlFilter: "\r\ngjgyl_bhdj= '2'",
                  cnName: 'II级',
                  type: 0,
                  enable: 0,
                  icon: null,
                  enName: 'gyl_ej',
                  sorting: 1040,
                  remark: null,
                  media: null,
                  fillColor: '#004586',
                  fillOpacity: '0.8',
                  strokeColor: null,
                  strokeWidth: null,
                  geoId: 200078,
                  geoBsm: 'forestry_public_welfare_2022_1726526712127262721',
                  workArea: 'lincao_resources_area',
                  dataPool: 'lincao_resources_db',
                  mapUrl: 'http://192.168.3.11:8001/geoserver/',
                  forestCode: 'forestry_public_welfare',
                  columnName: 'gjgyl_bhdj',
                  filterCondition: '2',
                  inOrEquals: 0,
                  childList: []
                }
              ]
            },
            {
              id: 1041,
              parentId: 1037,
              cqlFilter: '',
              cnName: '地方公益林',
              type: 1,
              enable: 0,
              icon: null,
              enName: 'gyl_dfgyl',
              sorting: 1041,
              remark: null,
              media: null,
              fillColor: null,
              fillOpacity: null,
              strokeColor: null,
              strokeWidth: null,
              geoId: 200078,
              geoBsm: 'forestry_public_welfare_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_public_welfare',
              columnName: null,
              filterCondition: null,
              inOrEquals: 0,
              childList: [
                {
                  id: 1042,
                  parentId: 1041,
                  cqlFilter: "ld_qs = '20'",
                  cnName: '地方公益林',
                  type: 0,
                  enable: 0,
                  icon: null,
                  enName: 'gyl_dfgyl',
                  sorting: 1042,
                  remark: null,
                  media: null,
                  fillColor: '#7ABEFF',
                  fillOpacity: '0.8',
                  strokeColor: null,
                  strokeWidth: null,
                  geoId: 200078,
                  geoBsm: 'forestry_public_welfare_2022_1726526712127262721',
                  workArea: 'lincao_resources_area',
                  dataPool: 'lincao_resources_db',
                  mapUrl: 'http://192.168.3.11:8001/geoserver/',
                  forestCode: 'forestry_public_welfare',
                  columnName: 'ld_qs',
                  filterCondition: '20',
                  inOrEquals: 0,
                  childList: []
                }
              ]
            }
          ]
        }
      ]
    },
    {
      id: 2010,
      parentId: -1,
      cqlFilter: null,
      cnName: '湿地资源',
      type: 1,
      enable: 0,
      icon: null,
      enName: 'forestry_wetland_style',
      sorting: 2010,
      remark: null,
      media: null,
      fillColor: '#DEED0B',
      fillOpacity: null,
      strokeColor: '#01040E',
      strokeWidth: null,
      geoId: 200077,
      geoBsm: 'forestry_wetland_2022_1726526712127262721',
      workArea: 'lincao_resources_area',
      dataPool: 'lincao_resources_db',
      mapUrl: 'http://192.168.3.11:8001/geoserver/',
      forestCode: 'forestry_wetland',
      columnName: 'tbbh',
      filterCondition: null,
      inOrEquals: 15,
      childList: [
        {
          id: 2011,
          parentId: 2010,
          cqlFilter: null,
          cnName: '湿地类型',
          type: 1,
          enable: 0,
          icon: null,
          enName: 'sdzy_lx',
          sorting: 2011,
          remark: null,
          media: null,
          fillColor: null,
          fillOpacity: null,
          strokeColor: null,
          strokeWidth: null,
          geoId: 200077,
          geoBsm: 'forestry_wetland_2022_1726526712127262721',
          workArea: 'lincao_resources_area',
          dataPool: 'lincao_resources_db',
          mapUrl: 'http://192.168.3.11:8001/geoserver/',
          forestCode: 'forestry_wetland',
          columnName: null,
          filterCondition: null,
          inOrEquals: 0,
          childList: [
            {
              id: 2012,
              parentId: 2011,
              cqlFilter: "dlbm = '0304'",
              cnName: '森林沼泽',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'sdzy_slzz',
              sorting: 2012,
              remark: null,
              media: null,
              fillColor: '#c7f075',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200077,
              geoBsm: 'forestry_wetland_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_wetland',
              columnName: 'dlbm',
              filterCondition: '0304',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 2013,
              parentId: 2011,
              cqlFilter: "dlbm = '0306'",
              cnName: '灌丛沼泽',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'sdzy_gczz',
              sorting: 2013,
              remark: null,
              media: null,
              fillColor: '#c5ee78',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200077,
              geoBsm: 'forestry_wetland_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_wetland',
              columnName: 'dlbm',
              filterCondition: '0306',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 2014,
              parentId: 2011,
              cqlFilter: "dlbm = '0402'",
              cnName: '沼泽草地',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'sdzy_zzcd',
              sorting: 2014,
              remark: null,
              media: null,
              fillColor: '#bee782',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200077,
              geoBsm: 'forestry_wetland_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_wetland',
              columnName: 'dlbm',
              filterCondition: '0402',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 2015,
              parentId: 2011,
              cqlFilter: "dlbm = '1105'",
              cnName: '沿海滩涂',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'sdzy_yhtt',
              sorting: 2015,
              remark: null,
              media: null,
              fillColor: '#80a5db',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200077,
              geoBsm: 'forestry_wetland_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_wetland',
              columnName: 'dlbm',
              filterCondition: '1105',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 2016,
              parentId: 2011,
              cqlFilter: "dlbm = '1106'",
              cnName: '内陆滩涂',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'sdzy_nltt',
              sorting: 2016,
              remark: null,
              media: null,
              fillColor: '#7ea3de',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200077,
              geoBsm: 'forestry_wetland_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_wetland',
              columnName: 'dlbm',
              filterCondition: '1106',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 2043,
              parentId: 2011,
              cqlFilter: "\r\ndlbm IN ('0304','0306,1108')",
              cnName: '沼泽地',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'sdzy_zzd',
              sorting: 2043,
              remark: null,
              media: null,
              fillColor: '#779be8',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200077,
              geoBsm: 'forestry_wetland_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_wetland',
              columnName: 'dlbm',
              filterCondition: '0304,0306,1108',
              inOrEquals: 1,
              childList: []
            },
            {
              id: 2044,
              parentId: 2011,
              cqlFilter: "dlbm = '0303'",
              cnName: '红树林地',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'sdzy_hsld',
              sorting: 2044,
              remark: null,
              media: null,
              fillColor: '#c9f371',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200077,
              geoBsm: 'forestry_wetland_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_wetland',
              columnName: 'dlbm',
              filterCondition: '0303',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 2045,
              parentId: 2011,
              cqlFilter: "dlbm IN ('1101','1102','1103','1104','1107')",
              cnName: '其他',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'qita',
              sorting: 2045,
              remark: null,
              media: null,
              fillColor: '#C9F371',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: '0',
              geoId: 200077,
              geoBsm: 'forestry_wetland_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_wetland',
              columnName: 'dlbm',
              filterCondition: '1101,1102,1103,1104,1107',
              inOrEquals: 1,
              childList: []
            }
          ]
        },
        {
          id: 100038,
          parentId: 2010,
          cqlFilter: null,
          cnName: '重要湿地',
          type: 1,
          enable: 0,
          icon: null,
          enName: null,
          sorting: 2012,
          remark: null,
          media: null,
          fillColor: '',
          fillOpacity: null,
          strokeColor: '',
          strokeWidth: null,
          geoId: 200077,
          geoBsm: 'forestry_wetland_2022_1726526712127262721',
          workArea: 'lincao_resources_area',
          dataPool: 'lincao_resources_db',
          mapUrl: 'http://192.168.3.11:8001/geoserver/',
          forestCode: 'forestry_wetland',
          columnName: '',
          filterCondition: '',
          inOrEquals: 0,
          childList: [
            {
              id: 100041,
              parentId: 100038,
              cqlFilter: "sd_dj = '3'",
              cnName: '省级重要湿地',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 2,
              remark: null,
              media: null,
              fillColor: '#BCF151',
              fillOpacity: '0.6',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200077,
              geoBsm: 'forestry_wetland_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_wetland',
              columnName: 'sd_dj',
              filterCondition: '3',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 100040,
              parentId: 100038,
              cqlFilter: "sd_dj = '1'",
              cnName: '国际重要湿地',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 3,
              remark: null,
              media: null,
              fillColor: '#51F1AE',
              fillOpacity: '0.6',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200077,
              geoBsm: 'forestry_wetland_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_wetland',
              columnName: 'sd_dj',
              filterCondition: '1',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 100039,
              parentId: 100038,
              cqlFilter: "sd_dj = '4'",
              cnName: '一般湿地',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 4,
              remark: null,
              media: null,
              fillColor: '#48E2F9',
              fillOpacity: '0.6',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200077,
              geoBsm: 'forestry_wetland_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_wetland',
              columnName: 'sd_dj',
              filterCondition: '4',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 100042,
              parentId: 100038,
              cqlFilter: "sd_dj = '2'",
              cnName: '其他国家重要湿地',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 5,
              remark: null,
              media: null,
              fillColor: '#FED048',
              fillOpacity: '0.6',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200077,
              geoBsm: 'forestry_wetland_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_wetland',
              columnName: 'sd_dj',
              filterCondition: '2',
              inOrEquals: 0,
              childList: []
            }
          ]
        }
      ]
    },
    {
      id: 3015,
      parentId: -1,
      cqlFilter: null,
      cnName: '草地资源',
      type: 1,
      enable: 0,
      icon: null,
      enName: 'forestry_grassland_style',
      sorting: 3015,
      remark: null,
      media: null,
      fillColor: '#ADB44E',
      fillOpacity: null,
      strokeColor: '#1143EB',
      strokeWidth: null,
      geoId: 200076,
      geoBsm: 'forestry_grassland_2022_1726526712127262721',
      workArea: 'lincao_resources_area',
      dataPool: 'lincao_resources_db',
      mapUrl: 'http://192.168.3.11:8001/geoserver/',
      forestCode: 'forestry_grassland',
      columnName: 'tbbh',
      filterCondition: null,
      inOrEquals: 20,
      childList: [
        {
          id: 100007,
          parentId: 3015,
          cqlFilter: null,
          cnName: '草地类型',
          type: 1,
          enable: 0,
          icon: null,
          enName: null,
          sorting: 3021,
          remark: null,
          media: null,
          fillColor: '',
          fillOpacity: null,
          strokeColor: '',
          strokeWidth: null,
          geoId: 200076,
          geoBsm: 'forestry_grassland_2022_1726526712127262721',
          workArea: 'lincao_resources_area',
          dataPool: 'lincao_resources_db',
          mapUrl: 'http://192.168.3.11:8001/geoserver/',
          forestCode: 'forestry_grassland',
          columnName: '',
          filterCondition: '',
          inOrEquals: 0,
          childList: [
            {
              id: 100008,
              parentId: 100007,
              cqlFilter: null,
              cnName: '草原型',
              type: 1,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 3022,
              remark: null,
              media: null,
              fillColor: '',
              fillOpacity: null,
              strokeColor: '',
              strokeWidth: null,
              geoId: 200076,
              geoBsm: 'forestry_grassland_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_grassland',
              columnName: '',
              filterCondition: '',
              inOrEquals: 0,
              childList: [
                {
                  id: 100017,
                  parentId: 100008,
                  cqlFilter: "cd_xing = '210283107'",
                  cnName: '羊草、贝加尔针茅型',
                  type: 0,
                  enable: 0,
                  icon: null,
                  enName: null,
                  sorting: 3031,
                  remark: null,
                  media: null,
                  fillColor: '#007BFF',
                  fillOpacity: '0.8',
                  strokeColor: null,
                  strokeWidth: null,
                  geoId: 200076,
                  geoBsm: 'forestry_grassland_2022_1726526712127262721',
                  workArea: 'lincao_resources_area',
                  dataPool: 'lincao_resources_db',
                  mapUrl: 'http://192.168.3.11:8001/geoserver/',
                  forestCode: 'forestry_grassland',
                  columnName: 'cd_xing',
                  filterCondition: '210283107',
                  inOrEquals: 0,
                  childList: []
                },
                {
                  id: 100018,
                  parentId: 100008,
                  cqlFilter: "cd_xing = '210283112'",
                  cnName: '羊草型',
                  type: 0,
                  enable: 0,
                  icon: null,
                  enName: null,
                  sorting: 3040,
                  remark: null,
                  media: null,
                  fillColor: '#4C4FF9',
                  fillOpacity: '0.8',
                  strokeColor: null,
                  strokeWidth: null,
                  geoId: 200076,
                  geoBsm: 'forestry_grassland_2022_1726526712127262721',
                  workArea: 'lincao_resources_area',
                  dataPool: 'lincao_resources_db',
                  mapUrl: 'http://192.168.3.11:8001/geoserver/',
                  forestCode: 'forestry_grassland',
                  columnName: 'cd_xing',
                  filterCondition: '210283112',
                  inOrEquals: 0,
                  childList: []
                },
                {
                  id: 100019,
                  parentId: 100008,
                  cqlFilter: "cd_xing = '210283104'",
                  cnName: '其他草原类',
                  type: 0,
                  enable: 0,
                  icon: null,
                  enName: null,
                  sorting: 3041,
                  remark: null,
                  media: null,
                  fillColor: '#42E0BB',
                  fillOpacity: '0.8',
                  strokeColor: null,
                  strokeWidth: '0',
                  geoId: 200076,
                  geoBsm: 'forestry_grassland_2022_1726526712127262721',
                  workArea: 'lincao_resources_area',
                  dataPool: 'lincao_resources_db',
                  mapUrl: 'http://192.168.3.11:8001/geoserver/',
                  forestCode: 'forestry_grassland',
                  columnName: 'cd_xing',
                  filterCondition: '210283104',
                  inOrEquals: 0,
                  childList: []
                }
              ]
            },
            {
              id: 100009,
              parentId: 100007,
              cqlFilter: null,
              cnName: '草原类',
              type: 1,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 3022,
              remark: null,
              media: null,
              fillColor: '',
              fillOpacity: null,
              strokeColor: '',
              strokeWidth: null,
              geoId: 200076,
              geoBsm: 'forestry_grassland_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_grassland',
              columnName: '',
              filterCondition: '',
              inOrEquals: 0,
              childList: [
                {
                  id: 100010,
                  parentId: 100009,
                  cqlFilter: "cd_l = '02'",
                  cnName: '温性典型草原类',
                  type: 0,
                  enable: 0,
                  icon: null,
                  enName: null,
                  sorting: 3024,
                  remark: null,
                  media: null,
                  fillColor: '#00FF26',
                  fillOpacity: '0.8',
                  strokeColor: null,
                  strokeWidth: '0',
                  geoId: 200076,
                  geoBsm: 'forestry_grassland_2022_1726526712127262721',
                  workArea: 'lincao_resources_area',
                  dataPool: 'lincao_resources_db',
                  mapUrl: 'http://192.168.3.11:8001/geoserver/',
                  forestCode: 'forestry_grassland',
                  columnName: 'cd_l',
                  filterCondition: '02',
                  inOrEquals: 0,
                  childList: []
                },
                {
                  id: 100011,
                  parentId: 100009,
                  cqlFilter: "cd_l = '01'",
                  cnName: '温性草甸草原类',
                  type: 0,
                  enable: 0,
                  icon: null,
                  enName: null,
                  sorting: 3025,
                  remark: null,
                  media: null,
                  fillColor: '#AEFF0D',
                  fillOpacity: '0.8',
                  strokeColor: null,
                  strokeWidth: null,
                  geoId: 200076,
                  geoBsm: 'forestry_grassland_2022_1726526712127262721',
                  workArea: 'lincao_resources_area',
                  dataPool: 'lincao_resources_db',
                  mapUrl: 'http://192.168.3.11:8001/geoserver/',
                  forestCode: 'forestry_grassland',
                  columnName: 'cd_l',
                  filterCondition: '01',
                  inOrEquals: 0,
                  childList: []
                },
                {
                  id: 100012,
                  parentId: 100009,
                  cqlFilter: "cd_l = '08'",
                  cnName: '低地草甸类',
                  type: 0,
                  enable: 0,
                  icon: null,
                  enName: null,
                  sorting: 3026,
                  remark: null,
                  media: null,
                  fillColor: '#0EFB79',
                  fillOpacity: '0.8',
                  strokeColor: null,
                  strokeWidth: null,
                  geoId: 200076,
                  geoBsm: 'forestry_grassland_2022_1726526712127262721',
                  workArea: 'lincao_resources_area',
                  dataPool: 'lincao_resources_db',
                  mapUrl: 'http://192.168.3.11:8001/geoserver/',
                  forestCode: 'forestry_grassland',
                  columnName: 'cd_l',
                  filterCondition: '08',
                  inOrEquals: 0,
                  childList: []
                },
                {
                  id: 100013,
                  parentId: 100009,
                  cqlFilter: "cd_l = '07'",
                  cnName: '高寒草甸类',
                  type: 0,
                  enable: 0,
                  icon: null,
                  enName: null,
                  sorting: 3027,
                  remark: null,
                  media: null,
                  fillColor: '#2BC671',
                  fillOpacity: '0.8',
                  strokeColor: null,
                  strokeWidth: null,
                  geoId: 200076,
                  geoBsm: 'forestry_grassland_2022_1726526712127262721',
                  workArea: 'lincao_resources_area',
                  dataPool: 'lincao_resources_db',
                  mapUrl: 'http://192.168.3.11:8001/geoserver/',
                  forestCode: 'forestry_grassland',
                  columnName: 'cd_l',
                  filterCondition: '07',
                  inOrEquals: 0,
                  childList: []
                },
                {
                  id: 100014,
                  parentId: 100009,
                  cqlFilter: "cd_l = '09'",
                  cnName: '山地草甸类',
                  type: 0,
                  enable: 0,
                  icon: null,
                  enName: null,
                  sorting: 3028,
                  remark: null,
                  media: null,
                  fillColor: '#9FF88D',
                  fillOpacity: '0.8',
                  strokeColor: null,
                  strokeWidth: null,
                  geoId: 200076,
                  geoBsm: 'forestry_grassland_2022_1726526712127262721',
                  workArea: 'lincao_resources_area',
                  dataPool: 'lincao_resources_db',
                  mapUrl: 'http://192.168.3.11:8001/geoserver/',
                  forestCode: 'forestry_grassland',
                  columnName: 'cd_l',
                  filterCondition: '09',
                  inOrEquals: 0,
                  childList: []
                },
                {
                  id: 100015,
                  parentId: 100009,
                  cqlFilter: "cd_l = '14'",
                  cnName: '暖性草丛类',
                  type: 0,
                  enable: 0,
                  icon: null,
                  enName: null,
                  sorting: 3029,
                  remark: null,
                  media: null,
                  fillColor: '#CAFF9C',
                  fillOpacity: '0.8',
                  strokeColor: null,
                  strokeWidth: null,
                  geoId: 200076,
                  geoBsm: 'forestry_grassland_2022_1726526712127262721',
                  workArea: 'lincao_resources_area',
                  dataPool: 'lincao_resources_db',
                  mapUrl: 'http://192.168.3.11:8001/geoserver/',
                  forestCode: 'forestry_grassland',
                  columnName: 'cd_l',
                  filterCondition: '14',
                  inOrEquals: 0,
                  childList: []
                },
                {
                  id: 100016,
                  parentId: 100009,
                  cqlFilter: "cd_l IN ('05','10','11','12','13')",
                  cnName: '其他草原类',
                  type: 0,
                  enable: 0,
                  icon: null,
                  enName: null,
                  sorting: 3030,
                  remark: null,
                  media: null,
                  fillColor: '#90E0C8',
                  fillOpacity: '0.8',
                  strokeColor: null,
                  strokeWidth: '0',
                  geoId: 200076,
                  geoBsm: 'forestry_grassland_2022_1726526712127262721',
                  workArea: 'lincao_resources_area',
                  dataPool: 'lincao_resources_db',
                  mapUrl: 'http://192.168.3.11:8001/geoserver/',
                  forestCode: 'forestry_grassland',
                  columnName: 'cd_l',
                  filterCondition: '14,09,08,15,02',
                  inOrEquals: 1,
                  childList: []
                }
              ]
            }
          ]
        },
        {
          id: 100020,
          parentId: 3015,
          cqlFilter: null,
          cnName: '基本草原',
          type: 1,
          enable: 0,
          icon: null,
          enName: null,
          sorting: 3022,
          remark: null,
          media: null,
          fillColor: '',
          fillOpacity: null,
          strokeColor: '',
          strokeWidth: null,
          geoId: 200076,
          geoBsm: 'forestry_grassland_2022_1726526712127262721',
          workArea: 'lincao_resources_area',
          dataPool: 'lincao_resources_db',
          mapUrl: 'http://192.168.3.11:8001/geoserver/',
          forestCode: 'forestry_grassland',
          columnName: '',
          filterCondition: '',
          inOrEquals: 0,
          childList: [
            {
              id: 100021,
              parentId: 100020,
              cqlFilter: "jbcyqk = '1'",
              cnName: '基本草原',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 1,
              remark: null,
              media: null,
              fillColor: '#76F474',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200076,
              geoBsm: 'forestry_grassland_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_grassland',
              columnName: 'jbcyqk',
              filterCondition: '1',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 100022,
              parentId: 100020,
              cqlFilter: "jbcyqk = '2'",
              cnName: '非基本草原',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 2,
              remark: null,
              media: null,
              fillColor: '#E3F475',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: '0',
              geoId: 200076,
              geoBsm: 'forestry_grassland_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_grassland',
              columnName: 'jbcyqk',
              filterCondition: '2',
              inOrEquals: 0,
              childList: []
            }
          ]
        }
      ]
    },
    {
      id: 4020,
      parentId: -1,
      cqlFilter: null,
      cnName: '森林资源',
      type: 1,
      enable: 0,
      icon: null,
      enName: 'forestry_resources_style',
      sorting: 4020,
      remark: null,
      media: null,
      fillColor: null,
      fillOpacity: null,
      strokeColor: null,
      strokeWidth: null,
      geoId: 200080,
      geoBsm: 'forestry_resources_2022_1726526712127262721',
      workArea: 'lincao_resources_area',
      dataPool: 'lincao_resources_db',
      mapUrl: 'http://192.168.3.11:8001/geoserver/',
      forestCode: 'forestry_resources',
      columnName: 'tbbh',
      filterCondition: null,
      inOrEquals: 0,
      childList: [
        {
          id: 100023,
          parentId: 4020,
          cqlFilter: null,
          cnName: '林种',
          type: 1,
          enable: 0,
          icon: null,
          enName: null,
          sorting: 4001,
          remark: null,
          media: null,
          fillColor: '',
          fillOpacity: null,
          strokeColor: '',
          strokeWidth: null,
          geoId: 200080,
          geoBsm: 'forestry_resources_2022_1726526712127262721',
          workArea: 'lincao_resources_area',
          dataPool: 'lincao_resources_db',
          mapUrl: 'http://192.168.3.11:8001/geoserver/',
          forestCode: 'forestry_resources',
          columnName: '',
          filterCondition: '',
          inOrEquals: 0,
          childList: [
            {
              id: 100024,
              parentId: 100023,
              cqlFilter: "lin_zhong = '111'",
              cnName: '水源涵养林',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 4001,
              remark: null,
              media: null,
              fillColor: '#C4FF21',
              fillOpacity: '1',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200080,
              geoBsm: 'forestry_resources_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_resources',
              columnName: 'lin_zhong',
              filterCondition: '111',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 100025,
              parentId: 100023,
              cqlFilter: "lin_zhong = '112'",
              cnName: '水土保持林',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 4002,
              remark: null,
              media: null,
              fillColor: '#FFEB57',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200080,
              geoBsm: 'forestry_resources_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_resources',
              columnName: 'lin_zhong',
              filterCondition: '112',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 100026,
              parentId: 100023,
              cqlFilter: "lin_zhong = '115'",
              cnName: '护岸林',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 4003,
              remark: null,
              media: null,
              fillColor: '#73FF57',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200080,
              geoBsm: 'forestry_resources_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_resources',
              columnName: 'lin_zhong',
              filterCondition: '115',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 100027,
              parentId: 100023,
              cqlFilter: "lin_zhong = '233'",
              cnName: '一般用材林',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 4004,
              remark: null,
              media: null,
              fillColor: '#57FFAE',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200080,
              geoBsm: 'forestry_resources_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_resources',
              columnName: 'lin_zhong',
              filterCondition: '233',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 100028,
              parentId: 100023,
              cqlFilter: "lin_zhong IN ('111','112','115','233')",
              cnName: '其他林种',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 4050,
              remark: null,
              media: null,
              fillColor: '#57EAE0',
              fillOpacity: '0.6',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200080,
              geoBsm: 'forestry_resources_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_resources',
              columnName: 'lin_zhong',
              filterCondition: '111,112,115,233',
              inOrEquals: 1,
              childList: []
            }
          ]
        },
        {
          id: 100029,
          parentId: 4020,
          cqlFilter: null,
          cnName: '林地保护等级',
          type: 1,
          enable: 0,
          icon: null,
          enName: null,
          sorting: 4002,
          remark: null,
          media: null,
          fillColor: '',
          fillOpacity: null,
          strokeColor: '',
          strokeWidth: null,
          geoId: 200080,
          geoBsm: 'forestry_resources_2022_1726526712127262721',
          workArea: 'lincao_resources_area',
          dataPool: 'lincao_resources_db',
          mapUrl: 'http://192.168.3.11:8001/geoserver/',
          forestCode: 'forestry_resources',
          columnName: '',
          filterCondition: '',
          inOrEquals: 0,
          childList: [
            {
              id: 100030,
              parentId: 100029,
              cqlFilter: "bh_dj = '1'",
              cnName: 'I级',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 1,
              remark: null,
              media: null,
              fillColor: '#C9ED3C',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: '0',
              geoId: 200080,
              geoBsm: 'forestry_resources_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_resources',
              columnName: 'bh_dj',
              filterCondition: '1',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 100031,
              parentId: 100029,
              cqlFilter: "bh_dj = '2'",
              cnName: 'II级',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 2,
              remark: null,
              media: null,
              fillColor: '#71ED3C',
              fillOpacity: '0.7',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200080,
              geoBsm: 'forestry_resources_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_resources',
              columnName: 'bh_dj',
              filterCondition: '2',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 100032,
              parentId: 100029,
              cqlFilter: "bh_dj = '3'",
              cnName: 'III级',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 3,
              remark: null,
              media: null,
              fillColor: '#6BFFC9',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200080,
              geoBsm: 'forestry_resources_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_resources',
              columnName: 'bh_dj',
              filterCondition: '3',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 100033,
              parentId: 100029,
              cqlFilter: "bh_dj = '4'",
              cnName: 'IV级',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 4,
              remark: null,
              media: null,
              fillColor: '#6BE6FF',
              fillOpacity: '0.6',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200080,
              geoBsm: 'forestry_resources_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_resources',
              columnName: 'bh_dj',
              filterCondition: '4',
              inOrEquals: 0,
              childList: []
            }
          ]
        },
        {
          id: 4021,
          parentId: 4020,
          cqlFilter: null,
          cnName: '植被覆盖类别',
          type: 1,
          enable: 0,
          icon: null,
          enName: 'slzy_lb',
          sorting: 4021,
          remark: null,
          media: null,
          fillColor: null,
          fillOpacity: null,
          strokeColor: null,
          strokeWidth: null,
          geoId: 200080,
          geoBsm: 'forestry_resources_2022_1726526712127262721',
          workArea: 'lincao_resources_area',
          dataPool: 'lincao_resources_db',
          mapUrl: 'http://192.168.3.11:8001/geoserver/',
          forestCode: 'forestry_resources',
          columnName: null,
          filterCondition: null,
          inOrEquals: 0,
          childList: [
            {
              id: 4024,
              parentId: 4021,
              cqlFilter: "zbfglx IN ('1130','1131','1132')",
              cnName: '竹林覆盖',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'slzy_gjjgyl',
              sorting: 4024,
              remark: null,
              media: null,
              fillColor: '#a1ffce',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200080,
              geoBsm: 'forestry_resources_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_resources',
              columnName: 'zbfglx',
              filterCondition: '1130,1131,1132',
              inOrEquals: 1,
              childList: []
            },
            {
              id: 4025,
              parentId: 4021,
              cqlFilter: "zbfglx IN ('1300','1310','1320')",
              cnName: '灌木覆盖',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'slzy_trl',
              sorting: 4025,
              remark: null,
              media: null,
              fillColor: '#bae2b6',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200080,
              geoBsm: 'forestry_resources_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_resources',
              columnName: 'zbfglx',
              filterCondition: '1300,1310,1320',
              inOrEquals: 1,
              childList: []
            },
            {
              id: 4026,
              parentId: 4021,
              cqlFilter: "zbfglx IN ('1400','1410','1420')",
              cnName: '幼树覆盖',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'slzy_rgl',
              sorting: 4026,
              remark: null,
              media: null,
              fillColor: '#86ae87',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200080,
              geoBsm: 'forestry_resources_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_resources',
              columnName: 'zbfglx',
              filterCondition: '1400,1410,1420',
              inOrEquals: 1,
              childList: []
            },
            {
              id: 4027,
              parentId: 4021,
              cqlFilter: "zbfglx IN ('2100')",
              cnName: '草本覆盖',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 4027,
              remark: null,
              media: null,
              fillColor: '#e3ff2d',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200080,
              geoBsm: 'forestry_resources_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_resources',
              columnName: 'zbfglx',
              filterCondition: '2100',
              inOrEquals: 1,
              childList: []
            },
            {
              id: 4028,
              parentId: 4021,
              cqlFilter:
                "zbfglx IN ('2000','2200','3000','3100','3200','3300','4100','4200','4300','5000')",
              cnName: '其他',
              type: 0,
              enable: 0,
              icon: null,
              enName: null,
              sorting: 4028,
              remark: null,
              media: null,
              fillColor: '#159244',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: '0',
              geoId: 200080,
              geoBsm: 'forestry_resources_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_resources',
              columnName: 'zbfglx',
              filterCondition:
                '2000,2200,3000,3100,3200,3300,4100,4200,4300,5000',
              inOrEquals: 1,
              childList: []
            }
          ]
        }
      ]
    },
    {
      id: 5027,
      parentId: -1,
      cqlFilter: null,
      cnName: '沙化荒漠化资源',
      type: 1,
      enable: 0,
      icon: null,
      enName: 'forestry_desert_style',
      sorting: 5027,
      remark: null,
      media: null,
      fillColor: null,
      fillOpacity: null,
      strokeColor: null,
      strokeWidth: null,
      geoId: 200079,
      geoBsm: 'forestry_desert_2022_1726526712127262721',
      workArea: 'lincao_resources_area',
      dataPool: 'lincao_resources_db',
      mapUrl: 'http://192.168.3.11:8001/geoserver/',
      forestCode: 'forestry_desert',
      columnName: 'tbbh',
      filterCondition: null,
      inOrEquals: 0,
      childList: [
        {
          id: 100034,
          parentId: 5027,
          cqlFilter: null,
          cnName: '沙化类型',
          type: 1,
          enable: 0,
          icon: null,
          enName: null,
          sorting: 1,
          remark: null,
          media: null,
          fillColor: '',
          fillOpacity: null,
          strokeColor: '',
          strokeWidth: null,
          geoId: 200079,
          geoBsm: 'forestry_desert_2022_1726526712127262721',
          workArea: 'lincao_resources_area',
          dataPool: 'lincao_resources_db',
          mapUrl: 'http://192.168.3.11:8001/geoserver/',
          forestCode: 'forestry_desert',
          columnName: '',
          filterCondition: '',
          inOrEquals: 0,
          childList: []
        },
        {
          id: 100035,
          parentId: 5027,
          cqlFilter: null,
          cnName: '沙漠化类型',
          type: 1,
          enable: 0,
          icon: null,
          enName: null,
          sorting: 2,
          remark: null,
          media: null,
          fillColor: '',
          fillOpacity: null,
          strokeColor: '',
          strokeWidth: null,
          geoId: 200079,
          geoBsm: 'forestry_desert_2022_1726526712127262721',
          workArea: 'lincao_resources_area',
          dataPool: 'lincao_resources_db',
          mapUrl: 'http://192.168.3.11:8001/geoserver/',
          forestCode: 'forestry_desert',
          columnName: '',
          filterCondition: '',
          inOrEquals: 0,
          childList: []
        },
        {
          id: 100036,
          parentId: 5027,
          cqlFilter: null,
          cnName: '沙化程度',
          type: 1,
          enable: 0,
          icon: null,
          enName: null,
          sorting: 3,
          remark: null,
          media: null,
          fillColor: '',
          fillOpacity: null,
          strokeColor: '',
          strokeWidth: null,
          geoId: 200079,
          geoBsm: 'forestry_desert_2022_1726526712127262721',
          workArea: 'lincao_resources_area',
          dataPool: 'lincao_resources_db',
          mapUrl: 'http://192.168.3.11:8001/geoserver/',
          forestCode: 'forestry_desert',
          columnName: '',
          filterCondition: '',
          inOrEquals: 0,
          childList: []
        },
        {
          id: 100037,
          parentId: 5027,
          cqlFilter: null,
          cnName: '荒漠化程度',
          type: 1,
          enable: 0,
          icon: null,
          enName: null,
          sorting: 4,
          remark: null,
          media: null,
          fillColor: '',
          fillOpacity: null,
          strokeColor: '',
          strokeWidth: null,
          geoId: 200079,
          geoBsm: 'forestry_desert_2022_1726526712127262721',
          workArea: 'lincao_resources_area',
          dataPool: 'lincao_resources_db',
          mapUrl: 'http://192.168.3.11:8001/geoserver/',
          forestCode: 'forestry_desert',
          columnName: '',
          filterCondition: '',
          inOrEquals: 0,
          childList: []
        },
        {
          id: 5028,
          parentId: 5027,
          cqlFilter: null,
          cnName: '防护林',
          type: 1,
          enable: 0,
          icon: null,
          enName: 'shhmhzy_fhl',
          sorting: 5028,
          remark: null,
          media: null,
          fillColor: null,
          fillOpacity: null,
          strokeColor: null,
          strokeWidth: null,
          geoId: 200079,
          geoBsm: 'forestry_desert_2022_1726526712127262721',
          workArea: 'lincao_resources_area',
          dataPool: 'lincao_resources_db',
          mapUrl: 'http://192.168.3.11:8001/geoserver/',
          forestCode: 'forestry_desert',
          columnName: 'lin_zhong',
          filterCondition: '110',
          inOrEquals: 0,
          childList: [
            {
              id: 5029,
              parentId: 5028,
              cqlFilter: "lin_zhong = '112'",
              cnName: '水土保持林',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'shhmhzy_stbcl',
              sorting: 5029,
              remark: null,
              media: null,
              fillColor: '#9f6cb2',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200079,
              geoBsm: 'forestry_desert_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_desert',
              columnName: 'lin_zhong',
              filterCondition: '112',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 5030,
              parentId: 5028,
              cqlFilter: "lin_zhong = '114'",
              cnName: '农用牧场防护林',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'shhmhzy_nymcfhl',
              sorting: 5030,
              remark: null,
              media: null,
              fillColor: '#c2a5cf',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200079,
              geoBsm: 'forestry_desert_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_desert',
              columnName: 'lin_zhong',
              filterCondition: '114',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 5031,
              parentId: 5028,
              cqlFilter: "lin_zhong = '113'",
              cnName: '防风固沙林',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'shhmhzy_ffgsl',
              sorting: 5031,
              remark: null,
              media: null,
              fillColor: '#b088c0',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200079,
              geoBsm: 'forestry_desert_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_desert',
              columnName: 'lin_zhong',
              filterCondition: '113',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 5032,
              parentId: 5028,
              cqlFilter: 'lin_zhong = 116',
              cnName: '护路护岸林',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'shhmhzy_hlhal',
              sorting: 5032,
              remark: null,
              media: null,
              fillColor: '#ddcee3',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: '0',
              geoId: 200079,
              geoBsm: 'forestry_desert_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_desert',
              columnName: 'lin_zhong',
              filterCondition: '116',
              inOrEquals: 0,
              childList: []
            }
          ]
        },
        {
          id: 5033,
          parentId: 5027,
          cqlFilter: null,
          cnName: '特殊用途林',
          type: 1,
          enable: 0,
          icon: null,
          enName: 'shhmhzy_tsytl',
          sorting: 5033,
          remark: null,
          media: null,
          fillColor: null,
          fillOpacity: null,
          strokeColor: null,
          strokeWidth: null,
          geoId: 200079,
          geoBsm: 'forestry_desert_2022_1726526712127262721',
          workArea: 'lincao_resources_area',
          dataPool: 'lincao_resources_db',
          mapUrl: 'http://192.168.3.11:8001/geoserver/',
          forestCode: 'forestry_desert',
          columnName: 'lin_zhong',
          filterCondition: '120',
          inOrEquals: 0,
          childList: [
            {
              id: 5034,
              parentId: 5033,
              cqlFilter: "lin_zhong = '121'",
              cnName: '国防林',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'shhmhzy_gfl',
              sorting: 5034,
              remark: null,
              media: null,
              fillColor: '#73f6ff',
              fillOpacity: '0.85',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200079,
              geoBsm: 'forestry_desert_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_desert',
              columnName: 'lin_zhong',
              filterCondition: '121',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 5035,
              parentId: 5033,
              cqlFilter: "lin_zhong = '122'",
              cnName: '实验林',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'shhmhzy_syl',
              sorting: 5035,
              remark: null,
              media: null,
              fillColor: '#42917b',
              fillOpacity: '0.85',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200079,
              geoBsm: 'forestry_desert_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_desert',
              columnName: 'lin_zhong',
              filterCondition: '122',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 5036,
              parentId: 5033,
              cqlFilter: "lin_zhong = '123'",
              cnName: '种子林',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'shhmhzy_zzl',
              sorting: 5036,
              remark: null,
              media: null,
              fillColor: '#bae2b6',
              fillOpacity: '0.85',
              strokeColor: null,
              strokeWidth: null,
              geoId: 200079,
              geoBsm: 'forestry_desert_2022_1726526712127262721',
              workArea: 'lincao_resources_area',
              dataPool: 'lincao_resources_db',
              mapUrl: 'http://192.168.3.11:8001/geoserver/',
              forestCode: 'forestry_desert',
              columnName: 'lin_zhong',
              filterCondition: '123',
              inOrEquals: 0,
              childList: []
            }
          ]
        }
      ]
    },
    {
      id: 8001,
      parentId: -1,
      cqlFilter: null,
      cnName: '项目使用林地',
      type: 1,
      enable: 0,
      icon: null,
      enName: 'use_woodland_style',
      sorting: 8001,
      remark: null,
      media: null,
      fillColor: null,
      fillOpacity: null,
      strokeColor: null,
      strokeWidth: null,
      geoId: null,
      geoBsm: null,
      workArea: null,
      dataPool: null,
      mapUrl: null,
      forestCode: null,
      columnName: 'tbbh',
      filterCondition: null,
      inOrEquals: 0,
      childList: [
        {
          id: 8002,
          parentId: 8001,
          cqlFilter: null,
          cnName: '使用性质',
          type: 1,
          enable: 0,
          icon: null,
          enName: 'use_type',
          sorting: 8002,
          remark: null,
          media: null,
          fillColor: null,
          fillOpacity: null,
          strokeColor: null,
          strokeWidth: null,
          geoId: null,
          geoBsm: null,
          workArea: null,
          dataPool: null,
          mapUrl: null,
          forestCode: null,
          columnName: null,
          filterCondition: null,
          inOrEquals: 0,
          childList: [
            {
              id: 8003,
              parentId: 8002,
              cqlFilter: "project_type = '基础设施'",
              cnName: '基础设施',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'use_jcss',
              sorting: 8003,
              remark: null,
              media: null,
              fillColor: '#ddcee3',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: null,
              geoBsm: null,
              workArea: null,
              dataPool: null,
              mapUrl: null,
              forestCode: null,
              columnName: 'project_type',
              filterCondition: '基础设施',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 8004,
              parentId: 8002,
              cqlFilter: "project_type = '公共事业和民生项目'",
              cnName: '公共事业和民生项目',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'use_ggsy',
              sorting: 8004,
              remark: null,
              media: null,
              fillColor: '#c2a5cf',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: null,
              geoBsm: null,
              workArea: null,
              dataPool: null,
              mapUrl: null,
              forestCode: null,
              columnName: 'project_type',
              filterCondition: '公共事业和民生项目',
              inOrEquals: 0,
              childList: []
            },
            {
              id: 8005,
              parentId: 8002,
              cqlFilter: "project_type = '城镇、园区建设项目'",
              cnName: '城镇、园区建设项目',
              type: 0,
              enable: 0,
              icon: null,
              enName: 'use_cz',
              sorting: 8005,
              remark: null,
              media: null,
              fillColor: '#b088c0',
              fillOpacity: '0.8',
              strokeColor: null,
              strokeWidth: null,
              geoId: null,
              geoBsm: null,
              workArea: null,
              dataPool: null,
              mapUrl: null,
              forestCode: null,
              columnName: 'project_type',
              filterCondition: '城镇、园区建设项目',
              inOrEquals: 0,
              childList: []
            }
          ]
        }
      ]
    },
    {
      id: 10001,
      parentId: -1,
      cqlFilter: null,
      cnName: '数据管理',
      type: 1,
      enable: 0,
      icon: null,
      enName: 'data_manage',
      sorting: 10001,
      remark: null,
      media: null,
      fillColor: null,
      fillOpacity: null,
      strokeColor: null,
      strokeWidth: null,
      geoId: null,
      geoBsm: null,
      workArea: null,
      dataPool: null,
      mapUrl: null,
      forestCode: null,
      columnName: 'tbbh',
      filterCondition: null,
      inOrEquals: 0,
      childList: [
        {
          id: 10010,
          parentId: 10001,
          cqlFilter: null,
          cnName: '古树名木',
          type: 0,
          enable: 0,
          icon: null,
          enName: 'gsmm',
          sorting: null,
          remark: null,
          media: null,
          fillColor: '#83a2ff',
          fillOpacity: '0.7',
          strokeColor: null,
          strokeWidth: null,
          geoId: null,
          geoBsm: null,
          workArea: null,
          dataPool: null,
          mapUrl: null,
          forestCode: null,
          columnName: null,
          filterCondition: null,
          inOrEquals: 0,
          childList: []
        },
        {
          id: 10011,
          parentId: 10001,
          cqlFilter: null,
          cnName: '自然保护地',
          type: 0,
          enable: 0,
          icon: null,
          enName: 'zrbhd',
          sorting: null,
          remark: null,
          media: null,
          fillColor: '#9f6cb2',
          fillOpacity: '0.7',
          strokeColor: null,
          strokeWidth: null,
          geoId: null,
          geoBsm: null,
          workArea: null,
          dataPool: null,
          mapUrl: null,
          forestCode: null,
          columnName: null,
          filterCondition: null,
          inOrEquals: 0,
          childList: []
        },
        {
          id: 10012,
          parentId: 10001,
          cqlFilter: null,
          cnName: '野生动物保护',
          type: 0,
          enable: 0,
          icon: null,
          enName: 'ysdwbh',
          sorting: null,
          remark: null,
          media: null,
          fillColor: '#c2a5cf',
          fillOpacity: '0.7',
          strokeColor: null,
          strokeWidth: null,
          geoId: null,
          geoBsm: null,
          workArea: null,
          dataPool: null,
          mapUrl: null,
          forestCode: null,
          columnName: null,
          filterCondition: null,
          inOrEquals: 0,
          childList: []
        },
        {
          id: 10013,
          parentId: 10001,
          cqlFilter: null,
          cnName: '林业产业企业分布',
          type: 0,
          enable: 0,
          icon: null,
          enName: 'lycyqyfb',
          sorting: null,
          remark: null,
          media: null,
          fillColor: '#b088c0',
          fillOpacity: '0.7',
          strokeColor: null,
          strokeWidth: null,
          geoId: null,
          geoBsm: null,
          workArea: null,
          dataPool: null,
          mapUrl: null,
          forestCode: null,
          columnName: null,
          filterCondition: null,
          inOrEquals: 0,
          childList: []
        },
        {
          id: 10014,
          parentId: 10001,
          cqlFilter: null,
          cnName: '森林督察',
          type: 0,
          enable: 0,
          icon: null,
          enName: 'sldc',
          sorting: null,
          remark: null,
          media: null,
          fillColor: '#ddcee3',
          fillOpacity: '0.7',
          strokeColor: null,
          strokeWidth: null,
          geoId: null,
          geoBsm: null,
          workArea: null,
          dataPool: null,
          mapUrl: null,
          forestCode: null,
          columnName: null,
          filterCondition: null,
          inOrEquals: 0,
          childList: []
        },
        {
          id: 10015,
          parentId: 10001,
          cqlFilter: null,
          cnName: '林地征占用',
          type: 0,
          enable: 0,
          icon: null,
          enName: 'ldzzy',
          sorting: null,
          remark: null,
          media: null,
          fillColor: '#fff15b',
          fillOpacity: '0.7',
          strokeColor: null,
          strokeWidth: null,
          geoId: null,
          geoBsm: null,
          workArea: null,
          dataPool: null,
          mapUrl: null,
          forestCode: null,
          columnName: null,
          filterCondition: null,
          inOrEquals: 0,
          childList: []
        },
        {
          id: 10016,
          parentId: 10001,
          cqlFilter: null,
          cnName: '天然林',
          type: 0,
          enable: 0,
          icon: null,
          enName: 'trl',
          sorting: null,
          remark: null,
          media: null,
          fillColor: '#73f6ff',
          fillOpacity: '0.7',
          strokeColor: null,
          strokeWidth: null,
          geoId: null,
          geoBsm: null,
          workArea: null,
          dataPool: null,
          mapUrl: null,
          forestCode: null,
          columnName: null,
          filterCondition: null,
          inOrEquals: 0,
          childList: []
        }
      ]
    },
    {
      id: 1057,
      parentId: 1001,
      cqlFilter: null,
      cnName: '公共基础数据',
      type: 1,
      enable: 0,
      icon: null,
      enName: 'ggjc_sj',
      sorting: 1057,
      remark: null,
      media: null,
      fillColor: null,
      fillOpacity: null,
      strokeColor: null,
      strokeWidth: null,
      geoId: null,
      geoBsm: null,
      workArea: null,
      dataPool: null,
      mapUrl: null,
      forestCode: null,
      columnName: null,
      filterCondition: null,
      inOrEquals: 0,
      childList: [
        {
          id: 1058,
          parentId: 1057,
          cqlFilter: null,
          cnName: '行政区划界线',
          type: 0,
          enable: 0,
          icon: null,
          enName: 'ggjc_xzqhjx',
          sorting: 1058,
          remark: null,
          media: null,
          fillColor: null,
          fillOpacity: null,
          strokeColor: null,
          strokeWidth: null,
          geoId: null,
          geoBsm: null,
          workArea: null,
          dataPool: null,
          mapUrl: null,
          forestCode: null,
          columnName: null,
          filterCondition: null,
          inOrEquals: 0,
          childList: []
        },
        {
          id: 1059,
          parentId: 1057,
          cqlFilter: null,
          cnName: '注记',
          type: 0,
          enable: 0,
          icon: null,
          enName: 'ggjc_zj',
          sorting: 1059,
          remark: null,
          media: null,
          fillColor: null,
          fillOpacity: null,
          strokeColor: null,
          strokeWidth: null,
          geoId: null,
          geoBsm: null,
          workArea: null,
          dataPool: null,
          mapUrl: null,
          forestCode: null,
          columnName: null,
          filterCondition: null,
          inOrEquals: 0,
          childList: []
        }
      ]
    }
  ]
};
