const getters = {
  sidebar: (state) => state.app.sidebar,
  language: (state) => state.app.language,
  size: (state) => state.app.size,
  device: (state) => state.app.device,
  visitedViews: (state) => state.tagsView.visitedViews,
  cachedViews: (state) => state.tagsView.cachedViews,
  token: (state) => state.user.token,
  level: (state) => state.user.level,
  areaCode: (state) => state.user.areaCode,
  areaName: (state) => state.user.areaName,
  unitCode: (state) => state.user.unitCode,
  roles: (state) => state.user.roles,
  permissions: (state) => state.user.permissions,
  permission_routes: (state) => state.permission.routes,
  errorLogs: (state) => state.errorLog.logs,
  dictionary: (state) => state.app.dictionary,
  requestLoading: (state) => state.app.requestLoading,
  allTreeData: (state) => state.app.allTreeData,
  user: (state) => state.user,
};
export default getters;
